#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
This is the script to put items into taskqueue.

It aims to helping other language, like php, to complete taskqueue.put action.
e.g. in php:
```
<?php
    $items = array('item1', 'item2');
    $cmd = "taskqueue-put /tmp/taskpool 1 " . escapeshellarg(json_encode($items));
    exec($cmd, $out, $returncode);
    if ($returncode == 0){
        do_something();
    }

?>
```

"""

import sys
from os.path import dirname, abspath
sys.path.append(dirname(dirname(abspath(__file__))))

if len(sys.argv) > 1 and sys.argv[1] in ('-h', '--help'):
    from os.path import basename
    print("usage: {} [-h] taskpool taskid json_string_of_items".format(basename(sys.argv[0])))
    exit(0)
if len(sys.argv) != 4:
    sys.stderr.write("3 arguments are required: taskpool taskid json_string_of_items\n")
    exit(1)


import json
from taskqueue import TaskQueue

taskpool, taskid, s = sys.argv[1:]
items = json.loads(s.strip())
q = TaskQueue(taskpool, taskid)
q.put(items)
